Console.WriteLine("Введите первое число a");
int numberA = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите второе число b");
int numberB = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите третье число с");
int numberC = Convert.ToInt32(Console.ReadLine());
int max = numberA;
if (numberA > max) max = numberA;
if (numberB > max) max = numberB;
if (numberC > max) max = numberC;
Console.Write("Максимальное число: ");
Console.WriteLine(max);
